import type { Metadata } from 'next';
import Script from 'next/script';
import '../public/css/bootstrap.min.css';
import '../public/css/common.css';
import '../public/css/main.css';
import '../public/css/responsive.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, overflowX: 'hidden', minHeight: '100vh' }}>
        {children}
      </body>
      <Script src="/js/bootstrap.bundle.min.js" />
      <Script src="/js/custom.js" />
    </html>
  );
}
