import type { Metadata } from 'next';
import Script from 'next/script';
import { Poppins } from 'next/font/google';
import '../public/css/bootstrap.min.css';
import '../public/css/common.css';
import '../public/css/main.css';
import '../public/css/responsive.css';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Buddy Script',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
        suppressHydrationWarning
        style={{ margin: 0, overflowX: 'hidden', minHeight: '100vh' }}
      >
        {children}
      </body>
      <Script src="/js/bootstrap.bundle.min.js" />
    </html>
  );
}
