export const POST_FEED_CACHE_TTL_SECONDS = 20;
export const POST_SUMMARY_CACHE_TTL_SECONDS = 60;
export const POST_LIKES_CACHE_TTL_SECONDS = 10;
export const MAX_POST_IMAGE_SIZE_BYTES = 8 * 1024 * 1024;

